// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SourceList struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SourceList) Reset()         { *m = SourceList{} }
func (m *SourceList) String() string { return proto.CompactTextString(m) }
func (*SourceList) ProtoMessage()    {}
func (*SourceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *SourceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceList.Unmarshal(m, b)
}
func (m *SourceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceList.Marshal(b, m, deterministic)
}
func (m *SourceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceList.Merge(m, src)
}
func (m *SourceList) XXX_Size() int {
	return xxx_messageInfo_SourceList.Size(m)
}
func (m *SourceList) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceList.DiscardUnknown(m)
}

var xxx_messageInfo_SourceList proto.InternalMessageInfo

func (m *SourceList) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type Source struct {
	Cid                  []byte   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Graph                string   `protobuf:"bytes,3,opt,name=graph,proto3" json:"graph,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *Source) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Source) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

type Blank struct {
	Cid                  []byte   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blank) Reset()         { *m = Blank{} }
func (m *Blank) String() string { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()    {}
func (*Blank) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *Blank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blank.Unmarshal(m, b)
}
func (m *Blank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blank.Marshal(b, m, deterministic)
}
func (m *Blank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blank.Merge(m, src)
}
func (m *Blank) XXX_Size() int {
	return xxx_messageInfo_Blank.Size(m)
}
func (m *Blank) XXX_DiscardUnknown() {
	xxx_messageInfo_Blank.DiscardUnknown(m)
}

var xxx_messageInfo_Blank proto.InternalMessageInfo

func (m *Blank) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *Blank) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Literal struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Datatype             string   `protobuf:"bytes,3,opt,name=datatype,proto3" json:"datatype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Literal) Reset()         { *m = Literal{} }
func (m *Literal) String() string { return proto.CompactTextString(m) }
func (*Literal) ProtoMessage()    {}
func (*Literal) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *Literal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Literal.Unmarshal(m, b)
}
func (m *Literal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Literal.Marshal(b, m, deterministic)
}
func (m *Literal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Literal.Merge(m, src)
}
func (m *Literal) XXX_Size() int {
	return xxx_messageInfo_Literal.Size(m)
}
func (m *Literal) XXX_DiscardUnknown() {
	xxx_messageInfo_Literal.DiscardUnknown(m)
}

var xxx_messageInfo_Literal proto.InternalMessageInfo

func (m *Literal) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Literal) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Literal) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

type Value struct {
	// Types that are valid to be assigned to Node:
	//	*Value_Iri
	//	*Value_Blank
	//	*Value_Literal
	Node                 isValue_Node `protobuf_oneof:"node"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Node interface {
	isValue_Node()
}

type Value_Iri struct {
	Iri string `protobuf:"bytes,1,opt,name=iri,proto3,oneof"`
}

type Value_Blank struct {
	Blank *Blank `protobuf:"bytes,2,opt,name=blank,proto3,oneof"`
}

type Value_Literal struct {
	Literal *Literal `protobuf:"bytes,3,opt,name=literal,proto3,oneof"`
}

func (*Value_Iri) isValue_Node() {}

func (*Value_Blank) isValue_Node() {}

func (*Value_Literal) isValue_Node() {}

func (m *Value) GetNode() isValue_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *Value) GetIri() string {
	if x, ok := m.GetNode().(*Value_Iri); ok {
		return x.Iri
	}
	return ""
}

func (m *Value) GetBlank() *Blank {
	if x, ok := m.GetNode().(*Value_Blank); ok {
		return x.Blank
	}
	return nil
}

func (m *Value) GetLiteral() *Literal {
	if x, ok := m.GetNode().(*Value_Literal); ok {
		return x.Literal
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Iri)(nil),
		(*Value_Blank)(nil),
		(*Value_Literal)(nil),
	}
}

type Index struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject              uint64   `protobuf:"varint,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            uint64   `protobuf:"varint,3,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               uint64   `protobuf:"varint,4,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Index) GetSubject() uint64 {
	if m != nil {
		return m.Subject
	}
	return 0
}

func (m *Index) GetPredicate() uint64 {
	if m != nil {
		return m.Predicate
	}
	return 0
}

func (m *Index) GetObject() uint64 {
	if m != nil {
		return m.Object
	}
	return 0
}

func init() {
	proto.RegisterType((*SourceList)(nil), "types.SourceList")
	proto.RegisterType((*Source)(nil), "types.Source")
	proto.RegisterType((*Blank)(nil), "types.Blank")
	proto.RegisterType((*Literal)(nil), "types.Literal")
	proto.RegisterType((*Value)(nil), "types.Value")
	proto.RegisterType((*Index)(nil), "types.Index")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0xe6, 0x9f, 0x99, 0xb4, 0x45, 0x16, 0x91, 0x20, 0x1e, 0x42, 0x10, 0x8c, 0x1e,
	0x7a, 0xa8, 0xf8, 0x05, 0x7a, 0x90, 0x0a, 0x3d, 0xad, 0xa0, 0xe7, 0x6d, 0x76, 0x89, 0xab, 0x21,
	0x09, 0xc9, 0x46, 0xf4, 0xdb, 0xcb, 0xce, 0x6c, 0xeb, 0xc5, 0x5b, 0x7e, 0xf3, 0xe7, 0xed, 0x7b,
	0x13, 0x48, 0xcd, 0x4f, 0xaf, 0xc6, 0x75, 0x3f, 0x74, 0xa6, 0x63, 0x21, 0x42, 0xf1, 0x08, 0xf0,
	0xd2, 0x4d, 0x43, 0xa5, 0xf6, 0x7a, 0x34, 0xec, 0x16, 0xe2, 0x11, 0x69, 0xcc, 0xbc, 0xdc, 0x2f,
	0xd3, 0xcd, 0x72, 0x4d, 0x3b, 0x34, 0xc3, 0x8f, 0xdd, 0xe2, 0x09, 0x22, 0x2a, 0xb1, 0x73, 0xf0,
	0x2b, 0x2d, 0x33, 0x2f, 0xf7, 0xca, 0x05, 0xb7, 0x9f, 0xec, 0x02, 0x42, 0xdd, 0x4a, 0xf5, 0x9d,
	0xcd, 0x73, 0xaf, 0x5c, 0x72, 0x02, 0x5b, 0xad, 0x07, 0xd1, 0xbf, 0x67, 0x7e, 0xee, 0x95, 0x09,
	0x27, 0x28, 0xee, 0x20, 0xdc, 0x36, 0xa2, 0xfd, 0xfc, 0x47, 0x66, 0x05, 0x73, 0x2d, 0x51, 0x23,
	0xe1, 0x73, 0x2d, 0x8b, 0x37, 0x88, 0xf7, 0xda, 0xa8, 0x41, 0x34, 0x56, 0xeb, 0x4b, 0x34, 0x93,
	0xc2, 0xf1, 0x84, 0x13, 0xb0, 0x2b, 0x38, 0x6b, 0x44, 0x5b, 0x4f, 0xa2, 0x56, 0x6e, 0xed, 0xc4,
	0xb6, 0x27, 0x85, 0x11, 0x36, 0x8c, 0x33, 0x70, 0xe2, 0x62, 0x82, 0xf0, 0x15, 0x05, 0x18, 0xf8,
	0x7a, 0xd0, 0x24, 0xba, 0x9b, 0x71, 0x0b, 0xec, 0x06, 0xc2, 0x83, 0x35, 0x88, 0x8a, 0xe9, 0x66,
	0xe1, 0xee, 0x81, 0xa6, 0x77, 0x33, 0x4e, 0x4d, 0x76, 0x0f, 0x71, 0x43, 0xde, 0x50, 0x3d, 0xdd,
	0xac, 0xdc, 0x9c, 0x73, 0xbc, 0x9b, 0xf1, 0xe3, 0xc0, 0x36, 0x82, 0xa0, 0xed, 0xa4, 0x2a, 0x6a,
	0x08, 0x9f, 0xf1, 0x32, 0x14, 0xd4, 0xbe, 0x1a, 0xd8, 0xa0, 0x2c, 0x83, 0x78, 0x9c, 0x0e, 0x1f,
	0xaa, 0x32, 0xf8, 0x68, 0xc0, 0x8f, 0xc8, 0xae, 0x21, 0xe9, 0x07, 0x25, 0x75, 0x25, 0x0c, 0xc5,
	0x08, 0xf8, 0x5f, 0x81, 0x5d, 0x42, 0xd4, 0xd1, 0x5a, 0x80, 0x2d, 0x47, 0x87, 0x08, 0x7f, 0xf8,
	0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x06, 0xdb, 0x18, 0xff, 0x01, 0x00, 0x00,
}
