package types

import (
	"encoding/binary"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	badger "github.com/dgraph-io/badger"
	proto "github.com/golang/protobuf/proto"
	cid "github.com/ipfs/go-cid"
	ld "github.com/piprate/json-gold/ld"
)

// GetValue serializes the source to a string.
func (source *Source) GetValue() string {
	if c, err := cid.Cast(source.Cid); err != nil {
		return ""
	} else {
		return fmt.Sprintf("ul:/ipfs/%s#/%d", c.String(), source.Index)
	}
}

// Value needs to satisfy the ld.Node interface, which means implementing
// GetValue() => string and Equal(ld.Node) => bool

var patternInteger = regexp.MustCompile("^[\\-+]?[0-9]+$")
var patternDouble = regexp.MustCompile("^(\\+|-)?([0-9]+(\\.[0-9]*)?|\\.[0-9]+)([Ee](\\+|-)?[0-9]+)?$")

// ToJSON casts the value into the appropriate JSON-LD interface
func (value *Value) ToJSON() (r interface{}) {
	if t, is := value.Node.(*Value_Blank); is {
		if c, err := cid.Cast(t.Blank.Cid); err == nil {
			uri := fmt.Sprintf("ul:/ipfs/%s#%s", c.String(), t.Blank.Id)
			r = map[string]interface{}{"@id": uri}
		}
	} else if t, is := value.Node.(*Value_Iri); is {
		r = map[string]interface{}{"@id": t.Iri}
	} else if t, is := value.Node.(*Value_Literal); is {
		v, d, l := t.Literal.Value, t.Literal.Datatype, t.Literal.Language
		if d == ld.RDFLangString {
			r = map[string]interface{}{"@value": v, "@language": l}
		} else if d == "" || d == ld.XSDString {
			r = v
		} else if d == ld.XSDBoolean {
			if v == "true" {
				r = true
			} else if v == "false" {
				r = false
			} else {
				r = map[string]interface{}{"@value": v, "@type": d}
			}
		} else if d == ld.XSDInteger && patternInteger.MatchString(v) {
			r, _ = strconv.Atoi(v)
		} else if d == ld.XSDDouble && patternDouble.MatchString(v) {
			r, _ = strconv.ParseFloat(v, 64)
		} else {
			r = map[string]interface{}{"@value": v, "@type": d}
		}
	}
	return
}

// GetValue serializes the value to a string.
func (value *Value) GetValue() string {
	if b, isBlank := value.Node.(*Value_Blank); isBlank {
		c, _ := cid.Cast(b.Blank.Cid)
		return fmt.Sprintf("<ul:/ipfs/%s#%s>", c.String(), b.Blank.Id)
	} else if i, isIri := value.Node.(*Value_Iri); isIri {
		return fmt.Sprintf("<%s>", i.Iri)
	} else if l, isLiteral := value.Node.(*Value_Literal); isLiteral {
		v, d, l := l.Literal.Value, l.Literal.Datatype, l.Literal.Language
		escaped := escape(v)
		if d == ld.RDFLangString {
			return fmt.Sprintf("\"%s\"@%s", escaped, l)
		} else if d != "" && d != ld.XSDString {
			return fmt.Sprintf("\"%s\"^^<%s>", escaped, d)
		} else {
			return fmt.Sprintf("\"%s\"", escaped)
		}
	} else {
		return ""
	}
}

func escape(str string) string {
	str = strings.Replace(str, "\\", "\\\\", -1)
	str = strings.Replace(str, "\"", "\\\"", -1)
	str = strings.Replace(str, "\n", "\\n", -1)
	str = strings.Replace(str, "\r", "\\r", -1)
	str = strings.Replace(str, "\t", "\\t", -1)
	return str
}

// Equal tests for equality between two ld.Nodes
func (value *Value) Equal(node ld.Node) bool {
	return value.GetValue() == node.GetValue()
}

// GetID satisfies the HasValue interface for index values by returning the index Id.
// The Index struct is generated by protobuf.
func (index *Index) GetID(_ interface{}) uint64 {
	return index.GetId()
}

// Increment the counter at the given position
func (index *Index) Increment(place uint8) {
	if place == 0 {
		index.Subject++
	} else if place == 1 {
		index.Predicate++
	} else if place == 2 {
		index.Object++
	}
}

// Get the counter at the given position
func (index *Index) Get(place uint8) uint64 {
	if place == 0 {
		return index.GetSubject()
	} else if place == 1 {
		return index.GetPredicate()
	} else if place == 2 {
		return index.GetObject()
	} else {
		return 0
	}
}

// An IndexMap associates marshalled string values with the
// Index structs that have already been read from the database.
// The Index struct is generated by protobuf.
type IndexMap map[string]*Index

// Commit writes the contents of the index map to badger
func (indexMap IndexMap) Commit(txn *badger.Txn) (err error) {
	var val []byte
	for v, index := range indexMap {
		key := AssembleKey(IndexPrefix, []byte(v), nil, nil)
		if val, err = proto.Marshal(index); err != nil {
			return
		} else if err = txn.Set(key, val); err != nil {
			return
		}
	}
	return
}

// Get memoizes database lookup for RDF nodes.
func (indexMap IndexMap) Get(node ld.Node, txn *badger.Txn) (*Index, error) {
	value := NodeToValue(cid.Undef, node).GetValue()
	if index, has := indexMap[value]; has {
		return index, nil
	}

	key := AssembleKey(IndexPrefix, []byte(value), nil, nil)
	if item, err := txn.Get(key); err != nil {
		return nil, err
	} else if val, err := item.ValueCopy(nil); err != nil {
		return nil, err
	} else {
		indexMap[value] = &Index{}
		if err = proto.Unmarshal(val, indexMap[value]); err != nil {
			return nil, err
		}
		return indexMap[value], nil
	}
}

// NodeToValue parses a cid.Cid and an ld.Node into a Value struct.
func NodeToValue(origin cid.Cid, node ld.Node) *Value {
	value := &Value{}
	if iri, isIri := node.(*ld.IRI); isIri {
		value.Node = &Value_Iri{Iri: iri.Value}
	} else if literal, isLiteral := node.(*ld.Literal); isLiteral {
		l := &Literal{Value: literal.Value}
		if literal.Datatype == ld.RDFLangString {
			l.Datatype = ld.RDFLangString
			l.Language = literal.Language
		} else if literal.Datatype != "" && literal.Datatype != ld.XSDString {
			l.Datatype = literal.Datatype
		}
		value.Node = &Value_Literal{l}
	} else if blank, isBlank := node.(*ld.BlankNode); isBlank {
		b := &Blank{Cid: origin.Bytes(), Id: blank.Attribute}
		value.Node = &Value_Blank{Blank: b}
	}
	return value
}

// A ValueMap associates uint64 ids with a value.
// The Value struct is generated by protobuf.
type ValueMap map[uint64]*Value

// Commit writes the contents of the value map to badger
func (values ValueMap) Commit(txn *badger.Txn) (err error) {
	var val []byte
	for id, v := range values {
		if val, err = proto.Marshal(v); err != nil {
			return err
		}

		key := make([]byte, 9)
		key[0] = ValuePrefix
		binary.BigEndian.PutUint64(key[1:], id)

		if err = txn.Set(key, val); err != nil {
			return
		}
	}
	return
}

// AssembleKey will look at the prefix byte to determine
// how many of the elements {abc} to pack into the key.
func AssembleKey(prefix byte, a, b, c []byte) []byte {
	A, B, C := len(a), len(b), len(c)
	key := make([]byte, 1+A+B+C)
	key[0] = prefix
	if A > 0 {
		copy(key[1:1+A], a)
		if B > 0 {
			copy(key[1+A:1+A+B], b)
			if C > 0 {
				copy(key[1+A+B:1+A+B+C], c)
			}
		}
	}
	return key
}

// PrintSources pretty-prints a slice of sources on a single line.
func PrintSources(sources []*Source) string {
	s := "[ "
	for i, source := range sources {
		c, _ := cid.Parse(source.Cid)
		if i > 0 {
			s += " | "
		}
		s += fmt.Sprintf("%s#%s/%d", c.String(), source.Graph, source.Index)
	}
	return s + " ]"
}
