// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Statement struct {
	Origin               uint64   `protobuf:"varint,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Graph                string   `protobuf:"bytes,3,opt,name=graph,proto3" json:"graph,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{0}
}

func (m *Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement.Unmarshal(m, b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement.Marshal(b, m, deterministic)
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return xxx_messageInfo_Statement.Size(m)
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

func (m *Statement) GetOrigin() uint64 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *Statement) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Statement) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

type SourceList struct {
	Sources              []*Statement `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SourceList) Reset()         { *m = SourceList{} }
func (m *SourceList) String() string { return proto.CompactTextString(m) }
func (*SourceList) ProtoMessage()    {}
func (*SourceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{1}
}

func (m *SourceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceList.Unmarshal(m, b)
}
func (m *SourceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceList.Marshal(b, m, deterministic)
}
func (m *SourceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceList.Merge(m, src)
}
func (m *SourceList) XXX_Size() int {
	return xxx_messageInfo_SourceList.Size(m)
}
func (m *SourceList) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceList.DiscardUnknown(m)
}

var xxx_messageInfo_SourceList proto.InternalMessageInfo

func (m *SourceList) GetSources() []*Statement {
	if m != nil {
		return m.Sources
	}
	return nil
}

type Blank struct {
	Origin               uint64   `protobuf:"varint,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blank) Reset()         { *m = Blank{} }
func (m *Blank) String() string { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()    {}
func (*Blank) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{2}
}

func (m *Blank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blank.Unmarshal(m, b)
}
func (m *Blank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blank.Marshal(b, m, deterministic)
}
func (m *Blank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blank.Merge(m, src)
}
func (m *Blank) XXX_Size() int {
	return xxx_messageInfo_Blank.Size(m)
}
func (m *Blank) XXX_DiscardUnknown() {
	xxx_messageInfo_Blank.DiscardUnknown(m)
}

var xxx_messageInfo_Blank proto.InternalMessageInfo

func (m *Blank) GetOrigin() uint64 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *Blank) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Literal struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Datatype             string   `protobuf:"bytes,3,opt,name=datatype,proto3" json:"datatype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Literal) Reset()         { *m = Literal{} }
func (m *Literal) String() string { return proto.CompactTextString(m) }
func (*Literal) ProtoMessage()    {}
func (*Literal) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{3}
}

func (m *Literal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Literal.Unmarshal(m, b)
}
func (m *Literal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Literal.Marshal(b, m, deterministic)
}
func (m *Literal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Literal.Merge(m, src)
}
func (m *Literal) XXX_Size() int {
	return xxx_messageInfo_Literal.Size(m)
}
func (m *Literal) XXX_DiscardUnknown() {
	xxx_messageInfo_Literal.DiscardUnknown(m)
}

var xxx_messageInfo_Literal proto.InternalMessageInfo

func (m *Literal) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Literal) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Literal) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

type Dataset struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{4}
}

func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (m *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(m, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Index struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject              uint64   `protobuf:"varint,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            uint64   `protobuf:"varint,3,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               uint64   `protobuf:"varint,4,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0f90c600ad7e2e, []int{5}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Index) GetSubject() uint64 {
	if m != nil {
		return m.Subject
	}
	return 0
}

func (m *Index) GetPredicate() uint64 {
	if m != nil {
		return m.Predicate
	}
	return 0
}

func (m *Index) GetObject() uint64 {
	if m != nil {
		return m.Object
	}
	return 0
}

func init() {
	proto.RegisterType((*Statement)(nil), "types.Statement")
	proto.RegisterType((*SourceList)(nil), "types.SourceList")
	proto.RegisterType((*Blank)(nil), "types.Blank")
	proto.RegisterType((*Literal)(nil), "types.Literal")
	proto.RegisterType((*Dataset)(nil), "types.Dataset")
	proto.RegisterType((*Index)(nil), "types.Index")
}

func init() { proto.RegisterFile("types/types.proto", fileDescriptor_2c0f90c600ad7e2e) }

var fileDescriptor_2c0f90c600ad7e2e = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4b, 0x84, 0x40,
	0x14, 0xc6, 0xd1, 0xd5, 0x35, 0x5f, 0x14, 0x35, 0x44, 0x58, 0x74, 0x10, 0x4f, 0xd2, 0x61, 0x17,
	0xea, 0xd2, 0x39, 0xba, 0x04, 0x0b, 0xc1, 0xec, 0xa1, 0xf3, 0x5b, 0x7d, 0xd8, 0x94, 0xa9, 0xcc,
	0x3c, 0xa3, 0xfe, 0xfb, 0x70, 0x66, 0xd6, 0x20, 0xd8, 0x8b, 0xf0, 0x7b, 0xcf, 0xc7, 0xf7, 0xfb,
	0x18, 0x38, 0xe7, 0x9f, 0x81, 0xcc, 0xda, 0x7e, 0x57, 0x83, 0xee, 0xb9, 0x17, 0xb1, 0x85, 0xe2,
	0x05, 0xd2, 0x2d, 0x23, 0xd3, 0x27, 0x75, 0x2c, 0x2e, 0x61, 0xd9, 0x6b, 0xd5, 0xa8, 0x2e, 0x0b,
	0xf2, 0xa0, 0x8c, 0xa4, 0x27, 0x71, 0x01, 0xb1, 0xea, 0x6a, 0xfa, 0xce, 0xc2, 0x3c, 0x28, 0x4f,
	0xa4, 0x83, 0x69, 0xda, 0x68, 0x1c, 0xde, 0xb2, 0x45, 0x1e, 0x94, 0xa9, 0x74, 0x50, 0x3c, 0x00,
	0x6c, 0xfb, 0x51, 0x57, 0xb4, 0x51, 0x86, 0xc5, 0x2d, 0x24, 0xc6, 0x92, 0xc9, 0x82, 0x7c, 0x51,
	0x1e, 0xdf, 0x9d, 0xad, 0x9c, 0xc4, 0x1c, 0x2a, 0xf7, 0x3f, 0x14, 0x6b, 0x88, 0x1f, 0x5b, 0xec,
	0x3e, 0x0e, 0x6a, 0x9c, 0x42, 0xa8, 0x6a, 0xeb, 0x90, 0xca, 0x50, 0xd5, 0xc5, 0x2b, 0x24, 0x1b,
	0xc5, 0xa4, 0xb1, 0x9d, 0x5c, 0xbe, 0xb0, 0x1d, 0xc9, 0x5e, 0xa4, 0xd2, 0x81, 0xb8, 0x86, 0xa3,
	0x16, 0xbb, 0x66, 0xc4, 0x86, 0xfc, 0xd9, 0xcc, 0xd3, 0xae, 0x46, 0xc6, 0xc9, 0xc6, 0x17, 0x98,
	0xb9, 0xb8, 0x82, 0xe4, 0x09, 0x19, 0x0d, 0xb1, 0xcf, 0x74, 0x1e, 0x53, 0x66, 0x03, 0xf1, 0xb3,
	0x6d, 0xff, 0x6f, 0x21, 0x32, 0x48, 0xcc, 0xb8, 0x7b, 0xa7, 0x8a, 0x6d, 0x54, 0x24, 0xf7, 0x28,
	0x6e, 0x20, 0x1d, 0x34, 0xd5, 0xaa, 0x42, 0x76, 0x51, 0x91, 0xfc, 0x1b, 0xd8, 0xb2, 0xee, 0x2c,
	0xf2, 0x65, 0x2d, 0xed, 0x96, 0xf6, 0x99, 0xee, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x6c,
	0xdc, 0x55, 0xbb, 0x01, 0x00, 0x00,
}
